backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO - Copy and paste first sentence of 'Body' Section here", name: "description", widget: "text", default: ""}
      - {label: "Featured Post (Select to highlight on homepage)", name: "featuredpost", widget: "boolean", default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, default: "/img/robert-hazel-headshot.png"}
      - {label: "Tags", name: "tags", widget: "list",  default: [""]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
      - file: "src/pages/resume/index.md"
        label: "Resume"
        name: "resume"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generic-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/scripts/index.md"
        label: "Scripts"
        name: "scripts"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generic-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/interviews/index.md"
        label: "Interviews"
        name: "interviews"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generic-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
